// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using School.Services.Courses.Infrastructure.Contexts;

namespace School.Services.Courses.Migrations
{
    [DbContext(typeof(CoursesDbContext))]
    partial class CoursesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("School.Services.Courses.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasMaxLength(100);

                    b.Property<string>("AuthorNameEn")
                        .HasMaxLength(100);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("UpdateOn");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new { AuthorId = 1, AuthorName = "علاء عباس الطير", AuthorNameEn = "Alaa Abbas Altair", CreatedOn = new DateTime(2019, 7, 31, 9, 5, 14, 123, DateTimeKind.Local), IsDelete = false }
                    );
                });

            modelBuilder.Entity("School.Services.Courses.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId");

                    b.Property<string>("CourseCategory")
                        .HasMaxLength(50);

                    b.Property<string>("CourseCategoryEn")
                        .HasMaxLength(50);

                    b.Property<string>("CourseName")
                        .HasMaxLength(50);

                    b.Property<string>("CourseNameEn")
                        .HasMaxLength(50);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("UpdateBy")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdateOn");

                    b.HasKey("CourseId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new { CourseId = 1, AuthorId = 1, CourseCategory = "شامل", CourseCategoryEn = "FullStack", CourseName = "دوره (.Net Core With React) ", CourseNameEn = ".Net Core With React", CreatedOn = new DateTime(2019, 7, 31, 9, 5, 14, 132, DateTimeKind.Local), IsDelete = false },
                        new { CourseId = 2, AuthorId = 1, CourseCategory = "تصمم وجهات", CourseCategoryEn = "FrontEnd", CourseName = "دوره (React With Redux)", CourseNameEn = "React With Redux", CreatedOn = new DateTime(2019, 7, 31, 9, 5, 14, 132, DateTimeKind.Local), IsDelete = false },
                        new { CourseId = 3, AuthorId = 1, CourseCategory = "برمجه", CourseCategoryEn = "BackEnd", CourseName = "دوره (.Net Core WebApi)", CourseNameEn = ".Net Core WebApi", CreatedOn = new DateTime(2019, 7, 31, 9, 5, 14, 132, DateTimeKind.Local), IsDelete = false }
                    );
                });

            modelBuilder.Entity("School.Services.Courses.Entities.Course", b =>
                {
                    b.HasOne("School.Services.Courses.Entities.Author", "Author")
                        .WithMany("Courses")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
